import { createTheme } from "@mui/material/styles";

export const DEFAULT_THEME = createTheme({
  palette: {
    mode: "light",
    common: {
      black: "#101828",
      white: "#ffffff",
    },
    primary: {
      main: "#0077AD",
      light: "#12ABDB",
      dark: "#2B0A3D",
      contrastText: "#ffffff",
    },
    secondary: {
      main: "#9a9a9a",
      light: "#cccccc",
      dark: "#636060",
      contrastText: "#202020",
    },
    error: {
      main: "#ff304d",
      light: "#ff455e",
      dark: "#e30021",
      contrastText: "#ffffff",
    },
    warning: {
      main: "#ff9c29",
      light: "#F8DD4E",
      dark: "#835101",
      contrastText: "#ffffff",
    },
    info: {
      main: "#00929b",
      light: "#00bfbf",
      dark: "#007d74",
      contrastText: "#ffffff",
    },
    success: {
      main: "#33b569",
      light: "#57cf80",
      dark: "#2ea657",
      contrastText: "#ffffff",
    },
    text: {
      primary: "#101828",
      secondary: "#667085",
      disabled: "#747474",
    },
    divider: "#9a9a9a",
    background: {
      paper: "#ffffff",
      default: "#F7F9FB",
    },
    grey: {
      100: "#f5f5f5",
      200: "#eaecf0",
      300: "#cccccc",
      500: "#667085",
    },
  },
  typography: {
    htmlFontSize: 20,
    fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
    fontSize: 18,
    fontWeightLight: 300,
    fontWeightRegular: 400,
    fontWeightMedium: 500,
    fontWeightBold: 700,
    h1: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 300,
      fontSize: "6rem",
      lineHeight: 1.167,
      letterSpacing: "-0.01562em",
    },
    h2: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 300,
      fontSize: "3.75rem",
      lineHeight: 1.2,
      letterSpacing: "-0.00833em",
    },
    h3: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "3rem",
      lineHeight: 1.167,
      letterSpacing: "0em",
    },
    h4: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 500,
      fontSize: "2rem",
      lineHeight: 1.235,
      letterSpacing: "0.00735em",
    },
    h5: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 500,
      fontSize: "1.5rem",
      lineHeight: 1.334,
      letterSpacing: "0em",
    },
    h6: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 500,
      fontSize: "1.25rem",
      lineHeight: 1.6,
      letterSpacing: "0.0075em",
    },
    subtitle1: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "1.125rem",
      lineHeight: 1.75,
      letterSpacing: "0.00938em",
    },
    subtitle2: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 500,
      fontSize: "1.0rem",
      lineHeight: 1.57,
      letterSpacing: "0.00714em",
    },
    body1: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "1rem",
      lineHeight: 1.5,
      letterSpacing: "0.00938em",
    },
    body2: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "0.875rem",
      lineHeight: 1.1,
      letterSpacing: "0.01071em",
    },
    button: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 500,
      fontSize: "1.25rem",
      lineHeight: 1.75,
      letterSpacing: "0.02857em",
      textTransform: "none",
    },
    caption: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "0.75rem",
      lineHeight: 1.66,
      letterSpacing: "0.03333em",
    },
    overline: {
      fontFamily: "'Ubuntu','Roboto','Helvetica','Ariel','sans-serif'",
      fontWeight: 400,
      fontSize: "0.75rem",
      lineHeight: 2.66,
      letterSpacing: "0.08333em",
      textTransform: "uppercase",
    },
  },
});
